AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  egoist-note

  Sample SAM Template for egoist-note

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  LineChannelAccessToken:
    Type: String
    Default: hoge
  LineChannelSecret:
    Type: String
    Default: fuga
  SystemType:
    Type: String
    AllowedValues:
      - general
    Default: general

# Lambda 関数名の Mapping 定義は以下も参照
# https://qiita.com/gotousua/items/48efb57cebef6d46f2ba#%E3%83%9E%E3%83%83%E3%83%94%E3%83%B3%E3%82%B0--mappings-
Mappings:
  SystemTypeMap:
    general:
      ApiHandlerLambdaName: egoist-note-api-handler

Resources:
  ApiHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Dependson: ApiHandlerLogGroup
    Properties:
      FunctionName:
        !FindInMap [SystemTypeMap, !Ref SystemType, ApiHandlerLambdaName]
      CodeUri: line_messaging_api/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          # このURLはコミット＆公開したくないため、デプロイ時にコマンドで設定する
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
          LINE_CHANNEL_SECRET: !Ref LineChannelSecret
      Events:
        API:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api_endpoint
            Method: post

  # api-handler 関数用のロググループ
  ApiHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        !Join [
          "",
          [
            /aws/lambda/,
            !FindInMap [SystemTypeMap, !Ref SystemType, ApiHandlerLambdaName],
          ],
        ]
      RetentionInDays: 30

  NotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: egoist-note-notify
      CodeUri: notify/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
          LINE_CHANNEL_SECRET: !Ref LineChannelSecret
      Events:
        NotifyLine:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *) # 日本時間19時(退勤時間)に毎日通知する

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiHandlerFunctionEndpointURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api_endpoint/"
  ApiHandlerFunctionArn:
    Description: "API Handler Function ARN"
    Value: !GetAtt ApiHandlerFunction.Arn
  ApiHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for API Handler Function"
    Value: !GetAtt ApiHandlerFunctionRole.Arn
  NotifyFunctionArn:
    Description: "Notify Function ARN"
    Value: !GetAtt NotifyFunction.Arn
  NotifyFunctionIamRole:
    Description: "Implicit IAM Role created for Notify Function"
    Value: !GetAtt NotifyFunctionRole.Arn
